<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
	<testsuite errors="0" failures="9" file="tests.py" name="tests.PostTestCase-20200217051215" skipped="0" tests="10" time="0.023" timestamp="2020-02-17T05:12:15">
		<testcase classname="tests.PostTestCase" file="module3/tests.py" line="235" name="test_task10_make_migrations" time="0.010" timestamp="2020-02-17T05:12:15">
			<system-out>
<![CDATA[]]>			</system-out>
			<system-err>
<![CDATA[]]>			</system-err>
		</testcase>
		<testcase classname="tests.PostTestCase" file="module3/tests.py" line="111" name="test_task1_post_model_exists" time="0.001" timestamp="2020-02-17T05:12:15">
			<failure message="Did you create the `BlogPost` class?" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "/home/m7885709/django/python-django-models-authentication/module3/tests.py", line 115, in test_task1_post_model_exists
    self.assertTrue(self.class_found, msg="Did you create the `BlogPost` class?")
  File "/home/m7885709/django/python-django-models-authentication/support/SimplerTestCase.py", line 12, in assertTrue
    self.fail(msg or (str(expr) + "is not True"))
AssertionError: Did you create the `BlogPost` class?
]]>			</failure>
			<system-out>
<![CDATA[]]>			</system-out>
			<system-err>
<![CDATA[]]>			</system-err>
		</testcase>
		<testcase classname="tests.PostTestCase" file="module3/tests.py" line="120" name="test_task2_author_exists" time="0.001" timestamp="2020-02-17T05:12:15">
			<failure message="Did you import `django.conf`'s `settings`" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "/home/m7885709/django/python-django-models-authentication/module3/tests.py", line 127, in test_task2_author_exists
    self.assertTrue(self.settings_import_found, msg="Did you import `django.conf`'s `settings`")
  File "/home/m7885709/django/python-django-models-authentication/support/SimplerTestCase.py", line 12, in assertTrue
    self.fail(msg or (str(expr) + "is not True"))
AssertionError: Did you import `django.conf`'s `settings`
]]>			</failure>
			<system-out>
<![CDATA[]]>			</system-out>
			<system-err>
<![CDATA[]]>			</system-err>
		</testcase>
		<testcase classname="tests.PostTestCase" file="module3/tests.py" line="133" name="test_task3_body_exists" time="0.001" timestamp="2020-02-17T05:12:15">
			<failure message="Did you add the `body` field?" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "/home/m7885709/django/python-django-models-authentication/module3/tests.py", line 137, in test_task3_body_exists
    self.assertTrue(self.body_field_found, msg="Did you add the `body` field?")
  File "/home/m7885709/django/python-django-models-authentication/support/SimplerTestCase.py", line 12, in assertTrue
    self.fail(msg or (str(expr) + "is not True"))
AssertionError: Did you add the `body` field?
]]>			</failure>
			<system-out>
<![CDATA[]]>			</system-out>
			<system-err>
<![CDATA[]]>			</system-err>
		</testcase>
		<testcase classname="tests.PostTestCase" file="module3/tests.py" line="139" name="test_task4_postdate_exists" time="0.001" timestamp="2020-02-17T05:12:15">
			<failure message="Did you add the `postdate` field and parameters?" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "/home/m7885709/django/python-django-models-authentication/module3/tests.py", line 141, in test_task4_postdate_exists
    self.assertTrue(self.postdate_field_found, msg="Did you add the `postdate` field and parameters?")
  File "/home/m7885709/django/python-django-models-authentication/support/SimplerTestCase.py", line 12, in assertTrue
    self.fail(msg or (str(expr) + "is not True"))
AssertionError: Did you add the `postdate` field and parameters?
]]>			</failure>
			<system-out>
<![CDATA[]]>			</system-out>
			<system-err>
<![CDATA[]]>			</system-err>
		</testcase>
		<testcase classname="tests.PostTestCase" file="module3/tests.py" line="145" name="test_task5_str_exists" time="0.001" timestamp="2020-02-17T05:12:15">
			<failure message="Did you implement the `__str__` method in the `post` model class?" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "/home/m7885709/django/python-django-models-authentication/module3/tests.py", line 146, in test_task5_str_exists
    self.assertTrue(self.str_method_found, msg="Did you implement the `__str__` method in the `post` model class?")
  File "/home/m7885709/django/python-django-models-authentication/support/SimplerTestCase.py", line 12, in assertTrue
    self.fail(msg or (str(expr) + "is not True"))
AssertionError: Did you implement the `__str__` method in the `post` model class?
]]>			</failure>
			<system-out>
<![CDATA[]]>			</system-out>
			<system-err>
<![CDATA[]]>			</system-err>
		</testcase>
		<testcase classname="tests.PostTestCase" file="module3/tests.py" line="148" name="test_task6_get_abs_url_exists" time="0.000" timestamp="2020-02-17T05:12:15">
			<failure message="Did you implement the `get_absolute_url` method?" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "/home/m7885709/django/python-django-models-authentication/module3/tests.py", line 149, in test_task6_get_abs_url_exists
    self.assertTrue(self.get_abs_url_found, msg="Did you implement the `get_absolute_url` method?")
  File "/home/m7885709/django/python-django-models-authentication/support/SimplerTestCase.py", line 12, in assertTrue
    self.fail(msg or (str(expr) + "is not True"))
AssertionError: Did you implement the `get_absolute_url` method?
]]>			</failure>
			<system-out>
<![CDATA[]]>			</system-out>
			<system-err>
<![CDATA[]]>			</system-err>
		</testcase>
		<testcase classname="tests.PostTestCase" file="module3/tests.py" line="151" name="test_task7_register_model_in_admin" time="0.002" timestamp="2020-02-17T05:12:15">
			<failure message="Did you import `BlogPost`?" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "/home/m7885709/django/python-django-models-authentication/module3/tests.py", line 170, in test_task7_register_model_in_admin
    self.assertTrue(import_BlogPost_found, msg="Did you import `BlogPost`?")
  File "/home/m7885709/django/python-django-models-authentication/support/SimplerTestCase.py", line 12, in assertTrue
    self.fail(msg or (str(expr) + "is not True"))
AssertionError: Did you import `BlogPost`?
]]>			</failure>
			<system-out>
<![CDATA[]]>			</system-out>
			<system-err>
<![CDATA[]]>			</system-err>
		</testcase>
		<testcase classname="tests.PostTestCase" file="module3/tests.py" line="173" name="test_task8_update_views_with_BlogPost" time="0.002" timestamp="2020-02-17T05:12:15">
			<failure message="Did you import `BlogPost`?" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "/home/m7885709/django/python-django-models-authentication/module3/tests.py", line 203, in test_task8_update_views_with_BlogPost
    self.assertTrue(import_BlogPost_found, msg="Did you import `BlogPost`?")
  File "/home/m7885709/django/python-django-models-authentication/support/SimplerTestCase.py", line 12, in assertTrue
    self.fail(msg or (str(expr) + "is not True"))
AssertionError: Did you import `BlogPost`?
]]>			</failure>
			<system-out>
<![CDATA[]]>			</system-out>
			<system-err>
<![CDATA[]]>			</system-err>
		</testcase>
		<testcase classname="tests.PostTestCase" file="module3/tests.py" line="208" name="test_task9_update_post_view_with_BlogPost" time="0.003" timestamp="2020-02-17T05:12:15">
			<failure message="Did you remove the `try/catch` block?" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "/home/m7885709/django/python-django-models-authentication/module3/tests.py", line 231, in test_task9_update_post_view_with_BlogPost
    self.assertTrue(try_catch_found == False, msg="Did you remove the `try/catch` block?")
  File "/home/m7885709/django/python-django-models-authentication/support/SimplerTestCase.py", line 12, in assertTrue
    self.fail(msg or (str(expr) + "is not True"))
AssertionError: Did you remove the `try/catch` block?
]]>			</failure>
			<system-out>
<![CDATA[]]>			</system-out>
			<system-err>
<![CDATA[]]>			</system-err>
		</testcase>
	</testsuite>
</testsuites>
